"use client";

import { useEffect, useRef, useState } from "react";
import { useTranslations } from "next-intl";
import { Headphones, Play, AlertTriangle, Info } from "lucide-react";
import type { ItemView } from "@/lib/api";
import { MCQItem } from "./MCQItem";

type Props = {
  item: ItemView;
  choice: string | null;
  onChange: (id: string) => void;
  disabled: boolean;
};

/**
 * Listening item: forces single-play. The student clicks "Play audio", listens,
 * then answers an MCQ. Once played, the play button is disabled and replaced by
 * a "Audio finished" badge. We disable the native seek bar.
 */
export function ListeningItem({ item, choice, onChange, disabled }: Props) {
  const t = useTranslations("Exam.listening");
  const audioUrl = resolveAudioUrl(item.payload.audio_url);
  const transcript = item.payload.transcript ?? item.payload.passage ?? item.payload.prompt ?? "";
  const [phase, setPhase] = useState<"ready" | "playing" | "finished">("ready");
  const [audioUnavailable, setAudioUnavailable] = useState(false);
  const audioRef = useRef<HTMLAudioElement | null>(null);
  
  const phaseRef = useRef(phase);
  const utteranceRef = useRef<SpeechSynthesisUtterance | null>(null);

  useEffect(() => {
    phaseRef.current = phase;
  }, [phase]);

  // Reset on item change (next listening question gets a fresh play state)
  useEffect(() => {
    setPhase("ready");
    setAudioUnavailable(false);
    audioRef.current?.pause();
    audioRef.current = null;
    if (typeof window !== "undefined" && window.speechSynthesis) {
      window.speechSynthesis.cancel();
    }
    return () => {
      audioRef.current?.pause();
      audioRef.current = null;
      if (typeof window !== "undefined" && window.speechSynthesis) {
        window.speechSynthesis.cancel();
      }
    };
  }, [item.id]);

  function play() {
    if (audioUrl && !audioUnavailable && typeof window !== "undefined") {
      audioRef.current?.pause();
      const audio = new Audio(audioUrl);
      audio.preload = "auto";
      audio.volume = 1;
      audio.onended = () => {
        setPhase("finished");
        phaseRef.current = "finished";
        audioRef.current = null;
      };
      audio.onerror = () => {
        setAudioUnavailable(true);
        audioRef.current = null;
        playSpeechFallback();
      };
      audioRef.current = audio;
      setPhase("playing");
      phaseRef.current = "playing";
      audio.play().catch(() => {
        setAudioUnavailable(true);
        audioRef.current = null;
        playSpeechFallback();
      });
      return;
    }
    playSpeechFallback();
  }

  function playSpeechFallback() {
    if (!transcript || typeof window === "undefined" || !("speechSynthesis" in window)) {
      setPhase("finished");
      phaseRef.current = "finished";
      return;
    }

    window.speechSynthesis.cancel();
    
    const utterance = new SpeechSynthesisUtterance(transcript);
    utterance.lang = "en-US";
    utterance.rate = 0.92;
    
    utteranceRef.current = utterance;

    utterance.onend = () => {
      setPhase("finished");
      phaseRef.current = "finished";
      utteranceRef.current = null;
    };
    
    utterance.onerror = (e: any) => {
      console.error("SpeechSynthesis error:", e.error || e);
      setPhase("finished");
      phaseRef.current = "finished";
      utteranceRef.current = null;
    };

    window.speechSynthesis.speak(utterance);
    setPhase("playing");
    phaseRef.current = "playing";
  }

  const hasPlayablePrompt = Boolean(audioUrl || transcript);
  const isTTSFallback = audioUnavailable || !audioUrl;
  const instructions = item.payload.instructions ?? item.payload.context ?? null;

  return (
    <div className="mt-8 space-y-6">
      {/* TTS Warning Banner */}
      {isTTSFallback && phase !== "ready" && (
        <div className="flex items-start gap-3 rounded-xl border border-amber-500/30 bg-amber-500/5 px-4 py-3 text-sm">
          <AlertTriangle className="h-4 w-4 mt-0.5 text-amber-500 shrink-0" />
          <div>
            <p className="font-medium text-amber-700 dark:text-amber-300">
              ⚠ Demo Mode — Text-to-Speech
            </p>
            <p className="mt-1 text-amber-600/80 dark:text-amber-400/80 text-xs">
              This audio is generated by browser TTS. Real IELTS uses professional pre-recorded audio
              with natural accents and background context.
            </p>
          </div>
        </div>
      )}

      {/* Section instructions (real IELTS shows context before each part) */}
      {instructions && phase === "ready" && (
        <div className="flex items-start gap-3 rounded-xl border border-blue-500/20 bg-blue-500/5 px-4 py-3 text-sm">
          <Info className="h-4 w-4 mt-0.5 text-blue-500 shrink-0" />
          <div>
            <p className="font-medium text-blue-700 dark:text-blue-300">Instructions</p>
            <p className="mt-1 text-blue-600/80 dark:text-blue-400/80">{instructions}</p>
          </div>
        </div>
      )}

      {/* Audio panel */}
      <article className="rounded-2xl border border-[var(--color-border)] bg-white/5 p-6 md:p-8 shadow-sm dark:bg-black/20">
        <div className="flex items-center gap-3 text-[var(--color-muted-fg)]">
          <Headphones className="h-5 w-5" />
          <span className="text-sm font-semibold uppercase tracking-wider">
            {t("label")}
          </span>
          <span className="ml-auto rounded-full bg-red-500/10 px-2.5 py-0.5 text-[10px] font-bold uppercase tracking-wider text-red-600 dark:text-red-400">
            Plays once only
          </span>
        </div>
        <div className="mt-6 flex items-center gap-4">
          {phase === "ready" && (
            <button
              type="button"
              onClick={play}
              disabled={!hasPlayablePrompt}
              className="flex items-center gap-2 rounded-full bg-[var(--color-primary)] px-6 py-3 text-sm font-semibold text-[var(--color-primary-fg)] shadow-sm transition-all hover:bg-[var(--color-primary)]/90 disabled:opacity-40"
            >
              <Play className="h-4 w-4" />
              {t("play")}
            </button>
          )}
          {phase === "playing" && (
            <div className="flex items-center gap-3">
              <span className="rounded-full bg-amber-500/15 px-4 py-2 text-sm font-medium text-amber-700 dark:text-amber-300">
                {t("playing")}
              </span>
              {/* Audio wave animation */}
              <div className="flex items-center gap-0.5">
                {[1,2,3,4,5].map((i) => (
                  <div
                    key={i}
                    className="w-1 bg-[var(--color-primary)] rounded-full animate-pulse"
                    style={{
                      height: `${8 + Math.random() * 16}px`,
                      animationDelay: `${i * 0.15}s`,
                      animationDuration: '0.8s',
                    }}
                  />
                ))}
              </div>
            </div>
          )}
          {phase === "finished" && (
            <span className="rounded-full bg-emerald-500/15 px-4 py-2 text-sm font-medium text-emerald-700 dark:text-emerald-300">
              ✓ {t("finished")}
            </span>
          )}
        </div>
      </article>

      {/* MCQ — disabled until audio has been played at least once */}
      <MCQItem
        item={item}
        choice={choice}
        onChange={onChange}
        disabled={disabled || (hasPlayablePrompt && phase !== "finished")}
      />
      {phase === "ready" && (
        <p className="text-sm text-[var(--color-muted-fg)]">
          {hasPlayablePrompt ? t("singlePlayHint") : t("noAudio")}
        </p>
      )}
    </div>
  );
}

function resolveAudioUrl(audioUrl: string | undefined): string | undefined {
  if (!audioUrl) return undefined;

  const demoAudioMap: Record<string, string> = {
    "https://demo.aiexam.uz/audio/listening/library_dialog.mp3": "/audio/listening/library_dialog.m4a",
    "https://demo.aiexam.uz/audio/listening/lecture_climate.mp3": "/audio/listening/lecture_climate.m4a",
  };
  if (demoAudioMap[audioUrl]) return demoAudioMap[audioUrl];

  try {
    const parsed = new URL(audioUrl);
    if (parsed.hostname === "demo.aiexam.uz") return undefined;
  } catch {
    return audioUrl;
  }

  return audioUrl;
}
